import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react';import{afterEach,describe,it,expect,vi}from'vitest';import App from'./App';
afterEach(()=>{cleanup();localStorage.clear();vi.unstubAllGlobals()})
describe('App',()=>{
 it('starts with no domain, score, finding or history',()=>{render(<App/>);expect(screen.getByText('Aucun audit n’a encore été exécuté.')).toBeTruthy();expect(screen.getByLabelText('Domaine exact')).toHaveValue('');expect(screen.queryByText(/\/100/)).toBeNull();expect(screen.getByRole('button',{name:/Démarrer l’audit réel/})).toBeDisabled()})
 it('requires authorization and explicit operator validation',()=>{render(<App/>);fireEvent.change(screen.getByLabelText('Domaine exact'),{target:{value:'https://shop.test'}});const checks=screen.getAllByRole('checkbox');fireEvent.click(checks[0]);expect(screen.getByRole('button',{name:/Démarrer l’audit réel/})).toBeDisabled()})
 it('labels the local lab as fictional',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Simulation locale'}));expect(screen.getByText(/DONNÉES FICTIVES — MODE DÉMONSTRATION/)).toBeTruthy()})
 it('loads demo.local without enabling history',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({is_demo:true,target:'demo.local',id:'demo-session',domain:'demo.local',started_at:'2000-01-01T00:00:00Z',completed_at:'2000-01-01T00:00:00Z',request_count:0,scope:[],findings:[],headers:{},cookies:[],score:{value:100,formula:'demo',factors:[],previous_comparison:null}})}));render(<App/>);fireEvent.click(screen.getByRole('button',{name:/ouvrir la boutique/i}));await waitFor(()=>expect(screen.getByText('DONNÉES FICTIVES — MODE DÉMONSTRATION — NE CONSTITUE PAS UN AUDIT RÉEL.')).toBeTruthy());expect(screen.getByText(/Boutique de démonstration/)).toBeTruthy();expect(screen.getByText('Historique désactivé en mode démonstration.')).toBeTruthy()})
 it('shows an explicit blocking warning for an incomplete scan',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({is_demo:true,target:'demo.local',id:'demo-incomplete',domain:'demo.local',started_at:'2000-01-01T00:00:00Z',completed_at:'2000-01-01T00:00:00Z',request_count:1,scope:['https://demo.local/'],findings:[],headers:{},cookies:[],scan_completeness:'INCOMPLETE',scan_issues:[{kind:'TRANSPORT_ERROR',url:'https://demo.local/',required:true,status_code:null}],score:{value:100,formula:'demo',factors:[],previous_comparison:null}})}));render(<App/>);fireEvent.click(screen.getByRole('button',{name:/ouvrir la boutique/i}));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('SCAN INCOMPLET'));expect(screen.getByRole('alert')).toHaveTextContent('aucune décision PASS')})
 it('switches to Arabic RTL and persists the versioned locale',()=>{const{container}=render(<App/>);fireEvent.change(screen.getByLabelText('Langue'),{target:{value:'ar'}});expect(container.firstElementChild).toHaveAttribute('dir','rtl');expect(document.documentElement).toHaveAttribute('dir','rtl');expect(document.documentElement).toHaveAttribute('lang','ar');expect(screen.getByRole('heading',{name:'الترخيص'})).toBeTruthy();expect(JSON.parse(localStorage.getItem('logialog.ui.v1')||'{}')).toEqual({version:1,locale:'ar'});fireEvent.click(screen.getByRole('button',{name:'محاكاة محلية'}));expect(screen.getByText('تعرض مُحاكى')).toBeTruthy();expect(screen.queryByText('Exposition simulée')).toBeNull()})
 it('switches all visible report chrome to English',()=>{render(<App/>);fireEvent.change(screen.getByLabelText('Langue'),{target:{value:'en'}});expect(screen.getByRole('button',{name:'Authorization'})).toBeTruthy();expect(screen.getByLabelText('Exact domain')).toBeTruthy();expect(screen.getByRole('button',{name:/Start real audit/})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Report'}));expect(screen.getByRole('heading',{name:'Client report'})).toBeTruthy();expect(screen.getByText('HTML for the client, JSON for automation and SARIF 2.1.0 for CI tools.')).toBeTruthy();expect(screen.queryByText('Rapport client')).toBeNull()})
})
