import {useEffect,useMemo,useState} from 'react'
import {Activity,Archive,ChevronRight,FileCheck2,FileText,FlaskConical,LayoutDashboard,LockKeyhole,PackageSearch,Presentation,ScanSearch,ShieldCheck,Wrench} from 'lucide-react'
import {demoReportUrl,jsonExportUrl,loadComparison,loadDemo,reportUrl,runAudit,sarifExportUrl} from './api'
import type {AuditComparison,AuditResult,Finding,Status} from './types'
import {dateLocale,direction,readLocale,saveLocale,translate} from './i18n'
import type {Locale,TranslationKey,Translator} from './i18n'
import './styles.css'
import './modes.css'
import './report.css'
import './comparison.css'
import './i18n.css'
import './accessibility.css'
import './brand-theme.css'
import './scan-completeness.css'

const nav:[string,typeof LockKeyhole,TranslationKey][]=[['Autorisation',LockKeyhole,'authorization'],['Progression',Activity,'progress'],['Résumé exécutif',LayoutDashboard,'summary'],['Modules',PackageSearch,'modules'],['Vulnérabilités',ShieldCheck,'vulnerabilities'],['Headers & cookies',ScanSearch,'headers'],['Preuves',FileCheck2,'evidence'],['Simulation locale',FlaskConical,'lab'],['Remédiation',Wrench,'remediation'],['Rapport',FileText,'report']]
const statusKeys:Record<Status,TranslationKey>={CONFIRMED:'confirmed',LIKELY:'likely',REQUIRES_ACCESS:'requiresAccess',ASSET_RESIDUE:'assetResidue',NOT_AFFECTED:'notAffected',HARDENING:'hardening'}

function StatusTag({status,t}:{status:Status;t:Translator}){return <span className={`status ${status.toLowerCase()}`}>{t(statusKeys[status])}</span>}
function FindingRow({finding,presentation,t}:{finding:Finding;presentation:boolean;t:Translator}){return <details className="finding"><summary><div><strong>{finding.subject}</strong><small>{finding.cve||finding.version||t('unknownVersion')}</small></div><StatusTag status={finding.status} t={t}/><span className="severity">{finding.severity}</span><ChevronRight size={17}/></summary><div className="finding-detail"><p><b>{t('interpretation')}</b>{finding.interpretation}</p><p><b>{t('businessRisk')}</b>{finding.business_risk}</p><p><b>{t('correction')}</b>{finding.remediation}</p>{finding.access_required&&<p><b>{t('accessNeeded')}</b>{finding.access_required}</p>}{!presentation&&finding.evidence?.map((e,i)=><code key={i}>{e.excerpt}<span>SHA-256 {e.response_sha256.slice(0,16)}… · {t('confidence')} {e.confidence}</span></code>)}{finding.source&&<a href={finding.source} target="_blank" rel="noreferrer">{t('officialSource')}</a>}</div></details>}

export default function App(){
 const [locale,setLocale]=useState<Locale>(readLocale),[section,setSection]=useState('Autorisation'),[target,setTarget]=useState(''),[authorized,setAuthorized]=useState(false),[operatorValidated,setOperatorValidated]=useState(false),[maxRequests,setMaxRequests]=useState(20),[busy,setBusy]=useState(false),[error,setError]=useState(''),[audit,setAudit]=useState<AuditResult|null>(null),[comparison,setComparison]=useState<AuditComparison|null>(null),[presentation,setPresentation]=useState(false),[scoreOpen,setScoreOpen]=useState(false)
 const t=useMemo(()=>translate(locale),[locale]),sectionTitle=t(nav.find(([name])=>name===section)?.[2]||'authorization')
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=direction(locale)},[locale])
 function changeLocale(value:Locale){setLocale(value);saveLocale(value)}
 const counts=useMemo(()=>audit?.findings.reduce((a,f)=>({...a,[f.status]:(a[f.status]||0)+1}),{} as Record<string,number>)||{},[audit])
 async function start(){setError('');setBusy(true);setSection('Progression');try{const result=await runAudit({target,authorization_confirmed:authorized,max_requests:maxRequests,delay_seconds:1});setAudit(result);setComparison(await loadComparison(result.id).catch(()=>null));setSection('Résumé exécutif')}catch(e){setError(e instanceof Error?e.message:t('unexpectedError'));setSection('Autorisation')}finally{setBusy(false)}}
 async function demo(){setError('');setBusy(true);try{setAudit(await loadDemo());setComparison(null);setSection('Résumé exécutif')}catch(e){setError(e instanceof Error?e.message:t('unexpectedError'))}finally{setBusy(false)}}
 return <div className={`app ${presentation?'presentation':''}`} lang={locale} dir={direction(locale)}>
  <aside><div className="brand"><img src="/brand/logialog-full.png" alt="LOGIALOG — Agence de développement"/><span className="brand-product">Security Auditor</span></div><nav>{nav.map(([name,Icon,key])=><button key={name} className={section===name?'active':''} onClick={()=>setSection(name)}><Icon/>{t(key)}</button>)}</nav><div className="side-note"><b>{t('passiveOnly')}</b><span>{t('requestLimit')}</span><span>{t('noExploit')}</span></div></aside>
  <main>
  {audit?.is_demo&&<div className="demo-warning">{t('demoWarning')}</div>}
  {audit?.scan_completeness==='INCOMPLETE'&&<div className="scan-incomplete" role="alert"><b>{t('scanIncomplete')}</b><span>{t('scanIncompleteDetail')}</span></div>}
  <header><div className="header-title"><img className="mobile-logo" src="/brand/logialog-mark.png" alt="LOGIALOG"/><div><h1>{sectionTitle}</h1><p>{audit?<><b>{audit.is_demo?t('demoShop'):t('realAudit')}</b> · {audit.domain} · {audit.request_count} {t('requests')}</>:t('noAudit')}</p></div></div><div className="header-actions"><label className="language-picker"><span>{t('language')}</span><select aria-label={t('language')} value={locale} onChange={e=>changeLocale(e.target.value as Locale)}><option value="fr">FR</option><option value="en">EN</option><option value="ar">AR</option></select></label><button className="present" onClick={()=>setPresentation(!presentation)}><Presentation/> {presentation?t('exitPresentation'):t('presentation')}</button></div></header>
  {section==='Autorisation'&&<section className="authorization"><div className="intro"><div className="intro-logo"><img src="/brand/logialog-mark.png" alt=""/></div><div><h2>{t('prepare')}</h2><p>{t('safeDescription')}</p></div></div><form onSubmit={e=>{e.preventDefault();start()}}><label>{t('exactDomain')}<input type="url" placeholder="https://example.test" value={target} onChange={e=>setTarget(e.target.value)} required/></label><label>{t('limit')}<input type="number" min="1" max="20" value={maxRequests} onChange={e=>setMaxRequests(Number(e.target.value))}/></label><label className="check"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/><span>{t('ownerConfirm')}</span></label><label className="check"><input type="checkbox" checked={operatorValidated} onChange={e=>setOperatorValidated(e.target.checked)}/><span>{t('operatorConfirm')}</span></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={!authorized||!operatorValidated||!target||busy}><ScanSearch/> {t('start')}</button></form><div className="scope"><b>{t('separateModes')}</b><span>{t('emptyMode')}</span><button className="demo-button" onClick={demo} disabled={busy}>{t('openDemo')}</button><span>{t('demoMode')}</span><span>{t('realMode')}</span></div></section>}
  {section==='Progression'&&<section className="progress"><Activity/><h2>{t(busy?'auditRunning':'auditComplete')}</h2><p>{t(busy?'runningCopy':'completeCopy')}</p><div className="bar"><i className={busy?'moving':''}/></div></section>}
  {section==='Résumé exécutif'&&<Dashboard audit={audit} comparison={comparison} counts={counts} presentation={presentation} scoreOpen={scoreOpen} setScoreOpen={setScoreOpen} t={t}/>}
  {(section==='Modules'||section==='Vulnérabilités')&&<section><SectionTitle title={sectionTitle} copy={t('evidenceRule')}/><div className="findings">{audit?.findings.filter(f=>section==='Vulnérabilités'?f.cve:!f.subject.includes('policy')&&!f.subject.includes('options')).map(f=><FindingRow key={f.subject+f.status} finding={f} presentation={presentation} t={t}/>)||<Empty t={t}/>}</div></section>}
  {section==='Headers & cookies'&&<Headers audit={audit} t={t}/>}
  {section==='Preuves'&&<section><SectionTitle title={t('technicalEvidence')} copy={t('evidencePrivacy')}/><div className="evidence-list">{audit?.findings.flatMap(f=>f.evidence.map((e,i)=><article key={f.subject+i}><b>{f.subject}</b><a href={e.url}>{e.url}</a><code>{e.excerpt}</code><small>{e.detection_method} · {t('confidence')} {e.confidence} · {new Date(e.captured_at).toLocaleString(dateLocale(locale))}</small></article>))||<Empty t={t}/>}</div></section>}
  {section==='Simulation locale'&&<Lab t={t}/>}
  {section==='Remédiation'&&<Remediation t={t}/>}
  {section==='Rapport'&&<section><SectionTitle title={t('clientReport')} copy={t('reportFormats')}/>{audit?<div className="report-box"><FileText/><div><b>{t(audit.is_demo?'demoReportReady':'realReportReady')}</b><span>{audit.report_sha256?`SHA-256 ${audit.report_sha256}`:t('fictionalReport')}</span></div><div className="report-actions"><a className="primary" href={audit.is_demo?demoReportUrl():reportUrl(audit.id)} target="_blank" rel="noreferrer">{t('openPrint')}</a><a className="export-link" href={jsonExportUrl(audit)} download>{t('downloadJson')}</a><a className="export-link" href={sarifExportUrl(audit)} download>{t('downloadSarif')}</a></div></div>:<Empty t={t}/>}</section>}
  </main></div>
}

function SectionTitle({title,copy}:{title:string;copy:string}){return <div className="section-title"><h2>{title}</h2><p>{copy}</p></div>}
function Empty({t}:{t:Translator}){return <div className="empty"><Archive/><b>{t('noAudit')}</b><span>{t('emptyDetail')}</span></div>}
function Dashboard({audit,comparison,counts,presentation,scoreOpen,setScoreOpen,t}:{audit:AuditResult|null;comparison:AuditComparison|null;counts:Record<string,number>;presentation:boolean;scoreOpen:boolean;setScoreOpen:(value:boolean)=>void;t:Translator}){return <section>{!audit?<Empty t={t}/>:<><div className="score-panel"><div><span>{t(audit.is_demo?'demoScore':'calculatedScore')}</span><strong>{audit.score?.value}/100</strong></div><button onClick={()=>setScoreOpen(!scoreOpen)}>{t('understandScore')}</button>{scoreOpen&&<div className="score-details"><p>{audit.score?.formula}</p>{audit.score?.factors.map((factor,i)=><p key={factor.subject+i}><b>{factor.points > 0?'+':''}{factor.points}</b> {factor.subject} — {factor.reason}</p>)}</div>}</div><ComparisonSummary audit={audit} comparison={comparison} t={t}/><div className="metrics"><article><span className="dot red"/><strong>{counts.CONFIRMED||0}</strong><p>{t('confirmed')}</p></article><article><span className="dot amber"/><strong>{counts.LIKELY||0}</strong><p>{t('likely')}</p></article><article><span className="dot blue"/><strong>{counts.REQUIRES_ACCESS||0}</strong><p>{t('requiresAccess')}</p></article><article><span className="dot gray"/><strong>{counts.ASSET_RESIDUE||0}</strong><p>{t('assetResidue')}</p></article><article><span className="dot green"/><strong>{counts.HARDENING||0}</strong><p>{t('hardening')}</p></article></div><div className="dashboard-grid"><div><SectionTitle title={t('priorityResults')} copy={t('moduleNamesWarning')}/><div className="findings">{audit.findings.slice(0,6).map(f=><FindingRow key={f.subject+f.status} finding={f} presentation={presentation} t={t}/>)}</div></div><Headers audit={audit} t={t}/></div></>}</section>}
function ComparisonSummary({audit,comparison,t}:{audit:AuditResult;comparison:AuditComparison|null;t:Translator}){if(audit.is_demo)return <div className="comparison-note">{t('historyDisabled')}</div>;if(!comparison?.available)return <div className="comparison-note">{t('firstAudit')}</div>;const delta=comparison.score_delta??0;return <div className="comparison-summary"><div><span>{t('scoreChange')}</span><strong className={delta>=0?'positive':'negative'}>{delta>0?'+':''}{delta}</strong></div><div><span>{t('newFindings')}</span><strong>{comparison.added.length}</strong></div><div><span>{t('resolved')}</span><strong>{comparison.resolved.length}</strong></div><div><span>{t('changed')}</span><strong>{comparison.changed.length}</strong></div><div><span>{t('unchanged')}</span><strong>{comparison.unchanged_count}</strong></div></div>}
function Headers({audit,t}:{audit:AuditResult|null;t:Translator}){return <section className="headers"><SectionTitle title={t('headers')} copy={t('defenseChecks')}/>{audit?Object.entries(audit.headers).map(([k,v])=><div className="header-row" key={k}><b>{k}</b><StatusTag status={v==='Absent'?'HARDENING':'NOT_AFFECTED'} t={t}/><span>{v}</span></div>):<Empty t={t}/>}</section>}
function Lab({t}:{t:Translator}){return <section className="lab"><div className="lab-banner">{t('demoWarning')}</div><SectionTitle title={t('labTitle')} copy={t('labCopy')}/><div className="flow"><article><span>1</span><h3>{t('unvalidatedInput')}</h3><input aria-label={t('fictionalId')} value={t('fictionalId')} readOnly/></article><article className="unsafe"><span>2</span><h3>{t('unsafeConstruction')}</h3><code>{t('labUnsafe')}</code></article><article className="safe"><span>3</span><h3>{t('parameterizedFix')}</h3><code>{t('labSafe')}</code></article></div><div className="fiction"><h3>{t('simulatedExposure')}</h3><p>{t('fakeRecords')}</p><p>{t('possibleImpacts')}</p></div><p className="disclaimer">{t('labDisclaimer')}</p></section>}
function Remediation({t}:{t:Translator}){return <section><SectionTitle title={t('remediationPlan')} copy={t('remediationCopy')}/><div className="remediation"><article><b>{t('p0')}</b><p>{t('p0Copy')}</p></article><article><b>{t('p1')}</b><p>{t('p1Copy')}</p></article><article><b>{t('p2')}</b><p>{t('p2Copy')}</p></article></div></section>}
