from fastapi import FastAPI
from fastapi.responses import HTMLResponse

app = FastAPI(title="LOGIALOG local fictional lab")

PAGE = """<!doctype html><html lang='fr'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>Laboratoire local LOGIALOG</title><style>body{font:16px system-ui;background:#f8fafc;color:#10233f;margin:0}.banner{background:#b54708;color:white;padding:20px;text-align:center;font-weight:800}main{max-width:1000px;margin:auto;padding:30px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.box{background:#fff;border:1px solid #eee;border-radius:12px;padding:24px}code{display:block;background:#1e293b;color:#10b981;padding:18px;border-radius:10px;margin-top:10px}.safe{border-top:5px solid #15945a}.unsafe{border-top:5px solid #d84a58}.warning{border-left:5px solid #f29b16;padding:15px;background:#fff9eb}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body><div class='banner'>DONNÉES FICTIVES — MODE DÉMONSTRATION — NE CONSTITUE PAS UN AUDIT RÉEL.</div><main><h1>Simulation conceptuelle ybc_blog</h1><p>Cette page ne reçoit aucune cible et ne contient aucun payload exploitable.</p><div class='grid'><section class='box unsafe'><h2>Entrée non validée</h2><p>Un identifiant fictif est concaténé conceptuellement.</p><code>SELECT … WHERE id = [entrée non validée]</code></section><section class='box safe'><h2>Requête paramétrée</h2><p>L’entrée est validée et transmise séparément.</p><code>SELECT … WHERE id = ? — paramètres typés</code></section></div><section class='box'><h2>Exposition fictive illustrée</h2><p>4 faux articles · 3 faux comptes · 6 fausses commandes</p><p>Conséquences possibles : lecture et altération de données, vol de sessions, ou implantation d’un web skimmer si une chaîne d’exploitation supplémentaire existe.</p></section><section class='box'><h2>Correction</h2><ul><li>Requêtes préparées</li><li>Validation stricte</li><li>Mise à jour vers une version corrigée</li><li>Remplacement d’une copie nulled par une archive officielle</li></ul></section><p class='warning'>Cette démonstration illustre l’impact potentiel de la vulnérabilité publiée. Elle ne constitue pas une preuve que le site client a été exploité ou que sa version installée est vulnérable.</p></main></body></html>"""


@app.get("/", response_class=HTMLResponse)
def index() -> str:
    return PAGE
